// Code generated by MockGen. DO NOT EDIT.
// Source: contact_service.go

// Package service is a generated GoMock package.
package service

import (
	models "contacts-crud/cmd/contacts/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIContactRepository is a mock of IContactRepository interface.
type MockIContactRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIContactRepositoryMockRecorder
}

// MockIContactRepositoryMockRecorder is the mock recorder for MockIContactRepository.
type MockIContactRepositoryMockRecorder struct {
	mock *MockIContactRepository
}

// NewMockIContactRepository creates a new mock instance.
func NewMockIContactRepository(ctrl *gomock.Controller) *MockIContactRepository {
	mock := &MockIContactRepository{ctrl: ctrl}
	mock.recorder = &MockIContactRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIContactRepository) EXPECT() *MockIContactRepositoryMockRecorder {
	return m.recorder
}

// AddContact mocks base method.
func (m *MockIContactRepository) AddContact(contact models.Contact) (*models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddContact", contact)
	ret0, _ := ret[0].(*models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddContact indicates an expected call of AddContact.
func (mr *MockIContactRepositoryMockRecorder) AddContact(contact interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddContact", reflect.TypeOf((*MockIContactRepository)(nil).AddContact), contact)
}

// GetAllContacts mocks base method.
func (m *MockIContactRepository) GetAllContacts() ([]*models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllContacts")
	ret0, _ := ret[0].([]*models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllContacts indicates an expected call of GetAllContacts.
func (mr *MockIContactRepositoryMockRecorder) GetAllContacts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllContacts", reflect.TypeOf((*MockIContactRepository)(nil).GetAllContacts))
}

// GetContact mocks base method.
func (m *MockIContactRepository) GetContact(id string) (*models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContact", id)
	ret0, _ := ret[0].(*models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContact indicates an expected call of GetContact.
func (mr *MockIContactRepositoryMockRecorder) GetContact(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContact", reflect.TypeOf((*MockIContactRepository)(nil).GetContact), id)
}

// UpdateContactStatus mocks base method.
func (m *MockIContactRepository) UpdateContactStatus(id string) (*models.Contact, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContactStatus", id)
	ret0, _ := ret[0].(*models.Contact)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContactStatus indicates an expected call of UpdateContactStatus.
func (mr *MockIContactRepositoryMockRecorder) UpdateContactStatus(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContactStatus", reflect.TypeOf((*MockIContactRepository)(nil).UpdateContactStatus), id)
}
